### ISSUE TITLE
Update to GeoTessCPP 2.6.1

### ISSUE THREAD

**Issue by jkmacc-LANL** [LANL-Seismoacoustics/PyGeoTess#1]
We're currently wrapping (a very small part of) GeoTess 2.2.  Let's jump to 2.6.

**Comment by jkmacc-LANL** [comment]
Hi @pdhhammon!  We've started a Python wrapper for GeoTess, and we're looking to update our wrapper from GeoTess 2.2 to 2.6.  We've been vendering the GeoTess source code directly in PyGeoTess, but it occurred to me that there could be a smoother way to use your source code.  Has the GeoTess library been released to repositories like "apt" or "yum" for Linux, or "[conda](https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/building-conda-packages.html)" for cross-platform installs?  If so, we could delete the source code from PyGeoTess and simply rely on the library to be installed via a more standard installation path, like apt/yum or conda.  It could certainly ease installation for some users.  Thanks for humoring me! :-)

**Comment by pdhhammon** [comment]
Hi! It unfortunately has not been released to a repository like this. The source code is available on https://github.com/sandialabs/GeoTessCPP, or https://github.com/sandialabs/GeoTessJava, but releasing it to apt or yum may be something we consider doing in the future. Thank you for pointing that out, because I’m not sure it’s something we had previously considered.

Is there anything else I can help with in the meantime?

Thanks,
Patrick Hammond

From: jkmacc-LANL ***@***.***>
Sent: Tuesday, June 1, 2021 4:12 PM
To: LANL-Seismoacoustics/PyGeoTess ***@***.***>
Cc: Hammond, Patrick ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [LANL-Seismoacoustics/PyGeoTess] Update to GeoTessCPP 2.6.1 (#1)


Hi @pdhhammon<https://github.com/pdhhammon>! We've started a Python wrapper for GeoTess, and we're looking to update our wrapper from GeoTess 2.2 to 2.6. We've been vendering the GeoTess source code directly in PyGeoTess, but it occurred to me that there could be a smoother way to use your source code. Has the GeoTess library been released to repositories like "apt" or "yum" for Linux, or "conda<https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/building-conda-packages.html>" for cross-platform installs? If so, we could delete the source code from PyGeoTess and simply rely on the library to be installed via a more standard installation path, like apt/yum or conda. It could certainly ease installation for some users. Thanks for humoring me! :-)

**Comment by jkmacc-LANL** [comment]
Thanks for responding, Patrick.  I think commonly-used repositories could really ease installation and distribution, but I certainly understand that there may not be free energy to do so.  Thanks again!
